// sources.config.js — Central config for all news sources aggregated by pulse.ai

const SOURCES = [
  // ─── GROUP A: TAMANNA ───────────────────────────────────────────────────────
  {
    name: "Tesla",
    group: "Robotics",
    rssUrl: null, // No public RSS — using scraper
    fallbackScrapeUrl: "https://www.tesla.com/en_US/blog",
    logoUrl: "https://www.tesla.com/favicon.ico",
    color: "#e82127",
  },
  {
    name: "Apple",
    group: "Enterprise",
    rssUrl: "https://www.apple.com/newsroom/rss-feed.rss",
    fallbackScrapeUrl: "https://www.apple.com/newsroom/",
    logoUrl: "https://www.apple.com/favicon.ico",
    color: "#a2aaad",
  },
  {
    name: "Microsoft",
    group: "Platforms",
    rssUrl: "https://news.microsoft.com/feed/",
    fallbackScrapeUrl: "https://news.microsoft.com/",
    logoUrl: "https://www.microsoft.com/favicon.ico",
    color: "#00a4ef",
  },
  {
    name: "Amazon",
    group: "Platforms",
    rssUrl: "https://www.aboutamazon.com/news/rss",
    fallbackScrapeUrl: "https://www.aboutamazon.com/news",
    logoUrl: "https://www.amazon.com/favicon.ico",
    color: "#ff9900",
  },
  {
    name: "NVIDIA",
    group: "Platforms",
    rssUrl: "https://feeds.feedburner.com/nvidiablog",
    fallbackScrapeUrl: "https://blogs.nvidia.com",
    logoUrl: "https://www.nvidia.com/favicon.ico",
    color: "#76b900",
  },
  {
    name: "Netflix",
    group: "Enterprise",
    rssUrl: "https://netflixtechblog.com/feed",
    // Use jina.ai proxy as a more reliable scraper fallback when the origin
    // presents certificate or bot-protection issues.
    fallbackScrapeUrl: "https://r.jina.ai/http://netflixtechblog.com/",
    logoUrl: "https://www.netflix.com/favicon.ico",
    color: "#e50914",
  },
  {
    name: "Google",
    group: "Platforms",
    rssUrl: "https://blog.google/rss/",
    fallbackScrapeUrl: "https://blog.google/",
    logoUrl: "https://www.google.com/favicon.ico",
    color: "#4285f4",
  },

  // ─── GROUP B: AI Labs ───────────────────────────────────────────────────────
  {
    name: "OpenAI",
    group: "Models",
    rssUrls: [
      "https://openai.com/blog/rss.xml",
      "https://news.google.com/rss/search?q=OpenAI+AI+news&hl=en-US&gl=US&ceid=US:en"
    ],
    fallbackScrapeUrl: "https://openai.com/blog",
    logoUrl: "https://openai.com/favicon.ico",
    color: "#10a37f",
  },
  {
    name: "Anthropic",
    group: "Models",
    rssUrls: [
      "https://news.google.com/rss/search?q=Anthropic+AI+news&hl=en-US&gl=US&ceid=US:en"
    ],
    fallbackScrapeUrl: "https://r.jina.ai/http://www.anthropic.com/news",
    logoUrl: "https://www.anthropic.com/favicon.ico",
    color: "#d4612a",
  },
  {
    name: "Google DeepMind",
    group: "Models",
    rssUrls: [
      "https://deepmind.google/blog/rss.xml",
      "https://news.google.com/rss/search?q=Google+DeepMind+AI+news&hl=en-US&gl=US&ceid=US:en"
    ],
    fallbackScrapeUrl: "https://deepmind.google/discover/blog/",
    logoUrl: "https://deepmind.google/favicon.ico",
    color: "#1a73e8",
  },
  {
    name: "Perplexity",
    group: "Enterprise",
    rssUrl: "https://news.google.com/rss/search?q=Perplexity+AI+news&hl=en-US&gl=US&ceid=US:en",
    fallbackScrapeUrl: "https://r.jina.ai/http://blog.perplexity.ai",
    logoUrl: "https://www.perplexity.ai/favicon.ico",
    color: "#20b2aa",
  },
  {
    name: "Mistral",
    group: "Models",
    rssUrl: "https://news.google.com/rss/search?q=Mistral+AI+news&hl=en-US&gl=US&ceid=US:en",
    fallbackScrapeUrl: "https://mistral.ai/news",
    logoUrl: "https://mistral.ai/favicon.ico",
    color: "#ff7000",
  },

  // ─── GROUP C: Publications ─────────────────────────────────────────────────
  {
    name: "MIT Tech Review",
    group: "Enterprise",
    rssUrl: "https://www.technologyreview.com/feed/",
    fallbackScrapeUrl: "https://www.technologyreview.com/",
    logoUrl: "https://www.technologyreview.com/favicon.ico",
    color: "#a00000",
  },
  {
    name: "Wired AI",
    group: "Enterprise",
    rssUrl: "https://www.wired.com/feed/tag/artificial-intelligence/rss",
    fallbackScrapeUrl: "https://www.wired.com/tag/artificial-intelligence/",
    logoUrl: "https://www.wired.com/favicon.ico",
    color: "#ff0000",
  },
  {
    name: "VentureBeat",
    group: "Enterprise",
    rssUrl: "https://venturebeat.com/category/ai/feed/",
    fallbackScrapeUrl: "https://venturebeat.com/category/artificial-intelligence/",
    logoUrl: "https://venturebeat.com/favicon.ico",
    color: "#0070d1",
  },
  {
    name: "The Verge",
    group: "Enterprise",
    rssUrl: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    fallbackScrapeUrl: "https://www.theverge.com/ai-artificial-intelligence",
    logoUrl: "https://www.theverge.com/favicon.ico",
    color: "#ff3b30",
  },
  {
    name: "TechCrunch",
    group: "Enterprise",
    rssUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
    fallbackScrapeUrl: "https://techcrunch.com/category/artificial-intelligence/",
    logoUrl: "https://techcrunch.com/favicon.ico",
    color: "#0a84ff",
  },
  {
    name: "ArXiv AI",
    group: "Enterprise",
    rssUrl: "https://rss.arxiv.org/rss/cs.LG",
    fallbackScrapeUrl: "https://arxiv.org/list/cs.LG/recent",
    logoUrl: "https://arxiv.org/favicon.ico",
    color: "#b31b1b",
  },

  // ─── Additional AI Companies requested ───────────────────────────────────
  {
    name: "Meta AI",
    group: "Models",
    rssUrl: [
      "https://about.meta.com/blog/rss",
      "https://news.google.com/rss/search?q=Meta+AI+news&hl=en-US&gl=US&ceid=US:en"
    ],
    fallbackScrapeUrl: "https://about.meta.com/",
    logoUrl: "https://meta.com/favicon.ico",
    color: "#0b5fff",
  },
  {
    name: "xAI",
    group: "Models",
    rssUrl: "https://news.google.com/rss/search?q=xAI+AI+news&hl=en-US&gl=US&ceid=US:en",
    fallbackScrapeUrl: "https://x.ai/",
    logoUrl: "https://x.ai/favicon.ico",
    color: "#000000",
  },
  {
    name: "Cohere",
    group: "Models",
    rssUrl: "https://news.google.com/rss/search?q=Cohere+AI+news&hl=en-US&gl=US&ceid=US:en",
    fallbackScrapeUrl: "https://cohere.ai/",
    logoUrl: "https://cohere.ai/favicon.ico",
    color: "#00b3a6",
  },
  {
    name: "AI21 Labs",
    group: "Models",
    rssUrl: "https://news.google.com/rss/search?q=AI21+Labs+AI+news&hl=en-US&gl=US&ceid=US:en",
    fallbackScrapeUrl: "https://www.ai21.com/",
    logoUrl: "https://www.ai21.com/favicon.ico",
    color: "#ff6b6b",
  },
  {
    name: "Inflection AI",
    group: "Models",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.inflection.ai/",
    logoUrl: "https://www.inflection.ai/favicon.ico",
    color: "#6b5cff",
  },
  {
    name: "Adept",
    group: "Models",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.adept.ai/",
    logoUrl: "https://www.adept.ai/favicon.ico",
    color: "#ff8c00",
  },
  {
    name: "Amazon Web Services",
    group: "Platforms",
    rssUrl: "https://aws.amazon.com/blogs/machine-learning/feed/",
    fallbackScrapeUrl: "https://aws.amazon.com/blogs/machine-learning/",
    logoUrl: "https://aws.amazon.com/favicon.ico",
    color: "#ff9900",
  },
  {
    name: "Google Cloud AI",
    group: "Platforms",
    rssUrl: "https://cloud.google.com/blog/topics/ai-machine-learning/rss",
    fallbackScrapeUrl: "https://cloud.google.com/blog/topics/ai-machine-learning",
    logoUrl: "https://cloud.google.com/favicon.ico",
    color: "#4285f4",
  },
  {
    name: "Oracle AI",
    group: "Platforms",
    rssUrl: "https://www.oracle.com/news/rss.xml",
    fallbackScrapeUrl: "https://www.oracle.com/artificial-intelligence/",
    logoUrl: "https://www.oracle.com/favicon.ico",
    color: "#f80000",
  },
  {
    name: "IBM Watsonx",
    group: "Platforms",
    rssUrl: "https://www.ibm.com/blogs/watsonx/feed/",
    fallbackScrapeUrl: "https://www.ibm.com/watsonx",
    logoUrl: "https://www.ibm.com/favicon.ico",
    color: "#006699",
  },
  {
    name: "Snowflake",
    group: "Platforms",
    rssUrl: "https://www.snowflake.com/blog/feed/",
    fallbackScrapeUrl: "https://www.snowflake.com/blog/",
    logoUrl: "https://www.snowflake.com/favicon.ico",
    color: "#28a0e5",
  },
  {
    name: "Databricks",
    group: "Platforms",
    rssUrl: "https://databricks.com/blog/feed",
    fallbackScrapeUrl: "https://databricks.com/blog",
    logoUrl: "https://databricks.com/favicon.ico",
    color: "#ff6f00",
  },
  {
    name: "CoreWeave",
    group: "Platforms",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.coreweave.com/",
    logoUrl: "https://www.coreweave.com/favicon.ico",
    color: "#00a3a3",
  },
  {
    name: "Lambda Labs",
    group: "Platforms",
    rssUrl: null,
    fallbackScrapeUrl: "https://lambdalabs.com/blog",
    logoUrl: "https://lambdalabs.com/favicon.ico",
    color: "#222222",
  },
  {
    name: "AMD",
    group: "Hardware",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.amd.com/en/newsroom",
    logoUrl: "https://www.amd.com/favicon.ico",
    color: "#ed1c24",
  },
  {
    name: "Intel AI",
    group: "Hardware",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.intel.com/content/www/us/en/artificial-intelligence/overview.html",
    logoUrl: "https://www.intel.com/favicon.ico",
    color: "#0071c5",
  },
  {
    name: "Cerebras Systems",
    group: "Hardware",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.cerebras.net/",
    logoUrl: "https://www.cerebras.net/favicon.ico",
    color: "#8b0000",
  },
  {
    name: "Groq",
    group: "Hardware",
    rssUrl: "https://news.google.com/rss/search?q=Groq+AI+news&hl=en-US&gl=US&ceid=US:en",
    fallbackScrapeUrl: "https://www.groq.com/",
    logoUrl: "https://www.groq.com/favicon.ico",
    color: "#00b050",
  },
  {
    name: "SambaNova Systems",
    group: "Hardware",
    rssUrl: null,
    fallbackScrapeUrl: "https://sambanova.ai/",
    logoUrl: "https://sambanova.ai/favicon.ico",
    color: "#5b2c6f",
  },
  {
    name: "Tenstorrent",
    group: "Hardware",
    rssUrl: null,
    fallbackScrapeUrl: "https://tenstorrent.com/",
    logoUrl: "https://tenstorrent.com/favicon.ico",
    color: "#1f77b4",
  },
  {
    name: "Qualcomm AI",
    group: "Hardware",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.qualcomm.com/news/releases",
    logoUrl: "https://www.qualcomm.com/favicon.ico",
    color: "#ffb400",
  },
  {
    name: "Arm AI",
    group: "Hardware",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.arm.com/ai",
    logoUrl: "https://www.arm.com/favicon.ico",
    color: "#ef6c00",
  },
  {
    name: "Palantir",
    group: "Enterprise",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.palantir.com/",
    logoUrl: "https://www.palantir.com/favicon.ico",
    color: "#000033",
  },
  {
    name: "UiPath",
    group: "Enterprise",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.uipath.com/blog",
    logoUrl: "https://www.uipath.com/favicon.ico",
    color: "#ff5a00",
  },
  {
    name: "Scale AI",
    group: "Enterprise",
    rssUrl: null,
    fallbackScrapeUrl: "https://scale.com/blog",
    logoUrl: "https://scale.com/favicon.ico",
    color: "#1f8ef1",
  },
  {
    name: "Dataiku",
    group: "Enterprise",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.dataiku.com/blog/",
    logoUrl: "https://www.dataiku.com/favicon.ico",
    color: "#00a3e0",
  },
  {
    name: "C3 AI",
    group: "Enterprise",
    rssUrl: null,
    fallbackScrapeUrl: "https://c3.ai/",
    logoUrl: "https://c3.ai/favicon.ico",
    color: "#0070bb",
  },
  {
    name: "Writer",
    group: "Enterprise",
    rssUrl: "https://writer.com/blog/rss",
    fallbackScrapeUrl: "https://writer.com/blog/",
    logoUrl: "https://writer.com/favicon.ico",
    color: "#7b61ff",
  },
  {
    name: "Glean",
    group: "Enterprise",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.glean.com/blog/",
    logoUrl: "https://www.glean.com/favicon.ico",
    color: "#00b2a9",
  },
  {
    name: "Moveworks",
    group: "Enterprise",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.moveworks.com/",
    logoUrl: "https://www.moveworks.com/favicon.ico",
    color: "#ff2d55",
  },
  {
    name: "Notion AI",
    group: "Enterprise",
    rssUrl: null,
    fallbackScrapeUrl: "https://r.jina.ai/http://www.notion.so/blog",
    logoUrl: "https://www.notion.so/favicon.ico",
    color: "#000000",
  },
  {
    name: "GitHub Copilot",
    group: "Developers",
    rssUrl: "https://github.blog/feed/",
    fallbackScrapeUrl: "https://github.blog/",
    logoUrl: "https://github.com/favicon.ico",
    color: "#24292e",
  },
  {
    name: "Cursor",
    group: "Developers",
    rssUrl: null,
    fallbackScrapeUrl: "https://r.jina.ai/http://cursor.com/blog",
    logoUrl: "https://cursor.com/favicon.ico",
    color: "#1a1a1a",
  },
  {
    name: "Replit",
    group: "Developers",
    rssUrl: null,
    fallbackScrapeUrl: "https://r.jina.ai/http://replit.com/blog",
    logoUrl: "https://replit.com/favicon.ico",
    color: "#ff3b30",
  },
  {
    name: "Hugging Face",
    group: "Developers",
    rssUrl: null,
    fallbackScrapeUrl: "https://r.jina.ai/http://huggingface.co/blog",
    logoUrl: "https://huggingface.co/favicon.ico",
    color: "#ff9900",
  },
  {
    name: "Weights & Biases",
    group: "Developers",
    rssUrl: null,
    fallbackScrapeUrl: "https://r.jina.ai/http://wandb.ai/articles",
    logoUrl: "https://wandb.ai/favicon.ico",
    color: "#4b5563",
  },
  {
    name: "LangChain",
    group: "Developers",
    rssUrl: "https://blog.langchain.dev/rss.xml",
    fallbackScrapeUrl: "https://blog.langchain.dev/",
    logoUrl: "https://langchain.com/favicon.ico",
    color: "#00a86b",
  },
  {
    name: "Figure",
    group: "Robotics",
    rssUrl: "https://news.google.com/rss/search?q=Figure+AI+news&hl=en-US&gl=US&ceid=US:en",
    fallbackScrapeUrl: "https://figure.ai/news",
    logoUrl: "https://figure.ai/favicon.ico",
    color: "#0f172a",
  },
  {
    name: "Boston Dynamics",
    group: "Robotics",
    rssUrl: "https://www.bostondynamics.com/feed",
    fallbackScrapeUrl: "https://www.bostondynamics.com/",
    logoUrl: "https://www.bostondynamics.com/favicon.ico",
    color: "#0057b8",
  },
  {
    name: "Waymo",
    group: "Robotics",
    rssUrl: null,
    fallbackScrapeUrl: "https://blog.waymo.com/",
    logoUrl: "https://waymo.com/favicon.ico",
    color: "#00b0ff",
  },
  {
    name: "Cruise",
    group: "Robotics",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.getcruise.com/",
    logoUrl: "https://www.getcruise.com/favicon.ico",
    color: "#00c2a8",
  },
  {
    name: "Skild AI",
    group: "Robotics",
    rssUrl: null,
    fallbackScrapeUrl: "https://www.skild.ai/",
    logoUrl: "https://www.skild.ai/favicon.ico",
    color: "#6c5ce7",
  },
];

module.exports = SOURCES;