function buildDigestHtml(
  user,
  intelligence
) {

  const name =
    user?.name ||
    user?.displayName ||
    "there";

  const date =
    intelligence?.date ||
    new Date()
      .toISOString()
      .split("T")[0];

  const whatsHappening =
    intelligence?.executiveSummary
      ?.whatsHappening || [];

  const whyItMatters =
    intelligence?.executiveSummary
      ?.whyItMatters || [];

  const biggestStory =
    whatsHappening[0];

  return `
<!DOCTYPE html>
<html>

<head>

<meta charset="utf-8"/>

<meta
  name="viewport"
  content="width=device-width, initial-scale=1.0"
/>

<style>

body {

  margin: 0;

  padding: 0;

  background: #f4f6f8;

  font-family:
    -apple-system,
    BlinkMacSystemFont,
    "Segoe UI",
    Roboto,
    sans-serif;

  color: #222;
}

.container {

  max-width: 640px;

  margin: auto;

  background: white;

  padding: 24px;
}

.logo {

  font-size: 28px;

  font-weight: 700;

  letter-spacing: 1px;

  color: #111827;
}

.date {

  color: #6b7280;

  margin-top: 4px;

  margin-bottom: 24px;
}

.section-title {

  font-size: 18px;

  font-weight: 700;

  margin-top: 32px;

  margin-bottom: 16px;
}

.story-card {

  border-left: 4px solid #111827;

  background: #f9fafb;

  padding: 16px;

  border-radius: 8px;

  margin-bottom: 20px;
}

.company-pill {

  display: inline-block;

  background: #eef2ff;

  color: #3730a3;

  padding: 4px 10px;

  border-radius: 999px;

  font-size: 12px;

  font-weight: 600;

  margin-bottom: 8px;
}

.story-text {

  font-size: 15px;

  line-height: 1.5;
}

.list-item {

  padding: 12px 0;

  border-bottom: 1px solid #f1f5f9;
}

.list-item:last-child {

  border-bottom: none;
}

.company {

  font-size: 13px;

  font-weight: 700;

  color: #4f46e5;

  margin-bottom: 4px;
}

.text {

  font-size: 14px;

  line-height: 1.5;
}

.why-item {

  margin-bottom: 12px;

  font-size: 14px;

  line-height: 1.5;
}

.footer {

  margin-top: 40px;

  padding-top: 20px;

  border-top: 1px solid #e5e7eb;

  font-size: 12px;

  color: #6b7280;
}

.cta {

  margin-top: 24px;

  text-align: center;
}

.cta a {

  display: inline-block;

  background: #111827;

  color: white;

  text-decoration: none;

  padding: 12px 18px;

  border-radius: 8px;

  font-weight: 600;
}

</style>

</head>

<body>

<div class="container">

<div class="logo">
PULSE AI
</div>

<div class="date">
Daily AI Intelligence · ${date}
</div>

<p>
Hi ${name} 👋
</p>

<p>
Here's your personalized briefing from the AI companies you follow.

We've highlighted the most important developments, business implications, and emerging signals from your watchlist.
</p>

${
  biggestStory
    ? `
<div class="section-title">
🚨 Biggest Story
</div>

<div class="story-card">

<div class="company-pill">
${biggestStory.company}
</div>

<div class="story-text">
${biggestStory.text}
</div>

</div>
`
    : ""
}

<div class="section-title">
🔥 Top Developments
</div>

${whatsHappening
  .slice(1, 6)
  .map(
    item => `
<div class="list-item">

<div class="company">
${item.company}
</div>

<div class="text">
${item.text}
</div>

</div>
`
  )
  .join("")}

<div class="section-title">
💡 Why It Matters
</div>

${whyItMatters
  .slice(0, 5)
  .map(
    item => `
<div class="why-item">
• ${item.text}
</div>
`
  )
  .join("")}

<div class="cta">

<a href="https://pulse-ai.in">

Open Pulse AI →

</a>

</div>

<div class="footer">

Generated by Pulse AI

<br/><br/>

Tracking
${intelligence.companyCount}
 companies today.

</div>

</div>

</body>

</html>
`;
}

module.exports = {
  buildDigestHtml
};