import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";

export default function SharedInsight() {
  const { id } = useParams();
  const [card, setCard] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function loadCard() {
      try {
        setLoading(true);
        const response = await fetch(`/api/share-cards/${id}`);
        if (!response.ok) {
          throw new Error("Share card not found");
        }
        setCard(await response.json());
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }

    loadCard();
  }, [id]);

  const items = useMemo(
    () => (card?.items || []).slice(0, 7),
    [card]
  );

  if (loading) {
    return (
      <div className="shared-page">
        Loading insight...
      </div>
    );
  }

  if (error) {
    return (
      <div className="shared-page">
        {error}
      </div>
    );
  }

  return (
    <div className="shared-page">
      <div className="shared-card">
        <div className="shared-brand">pulse-ai</div>
        <div className="shared-label">SHAREABLE INTELLIGENCE</div>
        <h1>{card.title}</h1>
        <p className="shared-subtitle">{card.subtitle}</p>

        <div className="shared-items">
          {items.map((item, index) => (
            <div className="shared-item" key={`${item.text}-${index}`}>
              <span className="shared-index">
                {String(index + 1).padStart(2, "0")}
              </span>
              <span>
                {item.company && (
                  <strong>{item.company}: </strong>
                )}
                {item.text}
              </span>
            </div>
          ))}
        </div>

        <div className="shared-footer">
          <span>{card.period || "Generated by Pulse AI"}</span>
          <span>Tracked by Pulse AI</span>
        </div>
      </div>
    </div>
  );
}
